const data = {
  Huruf: [
    {
      id: 1,
      name: "huruf a",
      shortName: "a",
      desc: "ayo belajar huruf a.",
      image: "/assets/images/a.webp",
      video: "/assets/videos/A.webm",
      audio: "/assets/audios/a.mp3",
    },
    {
      id: 2,
      name: "huruf b",
      shortName: "b",
      desc: "ayo belajar huruf b.",
      image: "/assets/images/b.webp",
      video: "/assets/videos/B.webm",
      audio: "/assets/audios/b.mp3",
    },
    {
      id: 3,
      name: "huruf c",
      shortName: "c",
      desc: "ayo belajar huruf c.",
      image: "/assets/images/c.webp",
      video: "/assets/videos/C.webm",
      audio: "/assets/audios/c.mp3",
    },
    {
      id: 4,
      name: "huruf d",
      shortName: "d",
      desc: "ayo belajar huruf d.",
      image: "/assets/images/d.webp",
      video: "/assets/videos/D.webm",
      audio: "/assets/audios/d.mp3",
    },
    {
      id: 5,
      name: "huruf e",
      shortName: "e",
      desc: "ayo belajar huruf e.",
      image: "/assets/images/e.webp",
      video: "/assets/videos/E.webm",
      audio: "/assets/audios/e.mp3",
    },
    {
      id: 6,
      name: "huruf f",
      shortName: "f",
      desc: "ayo belajar huruf f.",
      image: "/assets/images/f.webp",
      video: "/assets/videos/F.webm",
      audio: "/assets/audios/f.mp3",
    },
    {
      id: 7,
      name: "huruf g",
      shortName: "g",
      desc: "ayo belajar huruf g.",
      image: "/assets/images/g.webp",
      video: "/assets/videos/G.webm",
      audio: "/assets/audios/g.mp3",
    },
    {
      id: 8,
      name: "huruf h",
      shortName: "h",
      desc: "ayo belajar huruf h.",
      image: "/assets/images/h.webp",
      video: "/assets/videos/H.webm",
      audio: "/assets/audios/h.mp3",
    },
    {
      id: 9,
      name: "huruf i",
      shortName: "i",
      desc: "ayo belajar huruf i.",
      image: "/assets/images/i.webp",
      video: "/assets/videos/I.webm",
      audio: "/assets/audios/i.mp3",
    },
    {
      id: 10,
      name: "huruf j",
      shortName: "j",
      desc: "ayo belajar huruf j.",
      image: "/assets/images/j.webp",
      video: "/assets/videos/J.webm",
      audio: "/assets/audios/j.mp3",
    },
    {
      id: 11,
      name: "huruf k",
      shortName: "k",
      desc: "ayo belajar huruf k.",
      image: "/assets/images/k.webp",
      video: "/assets/videos/K.webm",
      audio: "/assets/audios/k.mp3",
    },
    {
      id: 12,
      name: "huruf l",
      shortName: "l",
      desc: "ayo belajar huruf l.",
      image: "/assets/images/l.webp",
      video: "/assets/videos/L.webm",
      audio: "/assets/audios/l.mp3",
    },
    {
      id: 13,
      name: "huruf m",
      shortName: "m",
      desc: "ayo belajar huruf m.",
      image: "/assets/images/m.webp",
      video: "/assets/videos/M.webm",
      audio: "/assets/audios/m.mp3",
    },
    {
      id: 14,
      name: "huruf n",
      shortName: "n",
      desc: "ayo belajar huruf n.",
      image: "/assets/images/n.webp",
      video: "/assets/videos/N.webm",
      audio: "/assets/audios/n.mp3",
    },
    {
      id: 15,
      name: "huruf o",
      shortName: "o",
      desc: "ayo belajar huruf o.",
      image: "/assets/images/o.webp",
      video: "/assets/videos/O.webm",
      audio: "/assets/audios/o.mp3",
    },
    {
      id: 16,
      name: "huruf p",
      shortName: "p",
      desc: "ayo belajar huruf p.",
      image: "/assets/images/p.webp",
      video: "/assets/videos/P.webm",
      audio: "/assets/audios/p.mp3",
    },
    {
      id: 17,
      name: "huruf q",
      shortName: "q",
      desc: "ayo belajar huruf q.",
      image: "/assets/images/q.webp",
      video: "/assets/videos/Q.webm",
      audio: "/assets/audios/q.mp3",
    },
    {
      id: 18,
      name: "huruf r",
      shortName: "r",
      desc: "ayo belajar huruf r.",
      image: "/assets/images/r.webp",
      video: "/assets/videos/R.webm",
      audio: "/assets/audios/r.mp3",
    },
    {
      id: 19,
      name: "huruf s",
      shortName: "s",
      desc: "ayo belajar huruf s.",
      image: "/assets/images/s.webp",
      video: "/assets/videos/S.webm",
      audio: "/assets/audios/s.mp3",
    },
    {
      id: 20,
      name: "huruf t",
      shortName: "t",
      desc: "ayo belajar huruf t.",
      image: "/assets/images/t.webp",
      video: "/assets/videos/T.webm",
      audio: "/assets/audios/t.mp3",
    },
    {
      id: 21,
      name: "huruf u",
      shortName: "u",
      desc: "ayo belajar huruf u.",
      image: "/assets/images/u.webp",
      video: "/assets/videos/U.webm",
      audio: "/assets/audios/u.mp3",
    },
    {
      id: 22,
      name: "huruf v",
      shortName: "v",
      desc: "ayo belajar huruf v.",
      image: "/assets/images/v.webp",
      video: "/assets/videos/V.webm",
      audio: "/assets/audios/v.mp3",
    },
    {
      id: 23,
      name: "huruf w",
      shortName: "w",
      desc: "ayo belajar huruf w.",
      image: "/assets/images/w.webp",
      video: "/assets/videos/W.webm",
      audio: "/assets/audios/w.mp3",
    },
    {
      id: 24,
      name: "huruf x",
      shortName: "x",
      desc: "ayo belajar huruf x.",
      image: "/assets/images/x.webp",
      video: "/assets/videos/X.webm",
      audio: "/assets/audios/x.mp3",
    },
    {
      id: 25,
      name: "huruf y",
      shortName: "y",
      desc: "ayo belajar huruf y.",
      image: "/assets/images/y.webp",
      video: "/assets/videos/Y.webm",
      audio: "/assets/audios/y.mp3",
    },
    {
      id: 26,
      name: "huruf z",
      shortName: "z",
      desc: "ayo belajar huruf z.",
      image: "/assets/images/z.webp",
      video: "/assets/videos/Z.webm",
      audio: "/assets/audios/z.mp3",
    },
  ],
};

export default data;
