const data = {
  Huruf: [
    {
      id: 1,
      name: "huruf a",
      shortName: "a",
      desc: "ayo belajar huruf a.",
      image: "/assets/images/a.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/A.webm",
    },
    {
      id: 2,
      name: "huruf b",
      shortName: "b",
      desc: "ayo belajar huruf b.",
      image: "/assets/images/b.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/B.webm",
    },
    {
      id: 3,
      name: "huruf c",
      shortName: "c",
      desc: "ayo belajar huruf c.",
      image: "/assets/images/c.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/C.webm",
    },
    {
      id: 4,
      name: "huruf d",
      shortName: "d",
      desc: "ayo belajar huruf d.",
      image: "/assets/images/d.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/D.webm",
    },
    {
      id: 5,
      name: "huruf e",
      shortName: "e",
      desc: "ayo belajar huruf e.",
      image: "/assets/images/e.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/E.webm",
    },
    {
      id: 6,
      name: "huruf f",
      shortName: "f",
      desc: "ayo belajar huruf f.",
      image: "/assets/images/f.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/F.webm",
    },
    {
      id: 7,
      name: "huruf g",
      shortName: "g",
      desc: "ayo belajar huruf g.",
      image: "/assets/images/g.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/G.webm",
    },
    {
      id: 8,
      name: "huruf h",
      shortName: "h",
      desc: "ayo belajar huruf h.",
      image: "/assets/images/h.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/H.webm",
    },
    {
      id: 9,
      name: "huruf i",
      shortName: "i",
      desc: "ayo belajar huruf i.",
      image: "/assets/images/i.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/I.webm",
    },
    {
      id: 10,
      name: "huruf j",
      shortName: "j",
      desc: "ayo belajar huruf j.",
      image: "/assets/images/j.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/J.webm",
    },
    {
      id: 11,
      name: "huruf k",
      shortName: "k",
      desc: "ayo belajar huruf k.",
      image: "/assets/images/k.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/K.webm",
    },
    {
      id: 12,
      name: "huruf l",
      shortName: "l",
      desc: "ayo belajar huruf l.",
      image: "/assets/images/l.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/L.webm",
    },
    {
      id: 13,
      name: "huruf m",
      shortName: "m",
      desc: "ayo belajar huruf m.",
      image: "/assets/images/m.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/M.webm",
    },
    {
      id: 14,
      name: "huruf n",
      shortName: "n",
      desc: "ayo belajar huruf n.",
      image: "/assets/images/n.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/N.webm",
    },
    {
      id: 15,
      name: "huruf o",
      shortName: "o",
      desc: "ayo belajar huruf o.",
      image: "/assets/images/o.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/O.webm",
    },
    {
      id: 16,
      name: "huruf p",
      shortName: "p",
      desc: "ayo belajar huruf p.",
      image: "/assets/images/p.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/P.webm",
    },
    {
      id: 17,
      name: "huruf q",
      shortName: "q",
      desc: "ayo belajar huruf q.",
      image: "/assets/images/q.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Q.webm",
    },
    {
      id: 18,
      name: "huruf r",
      shortName: "r",
      desc: "ayo belajar huruf r.",
      image: "/assets/images/r.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/R.webm",
    },
    {
      id: 19,
      name: "huruf s",
      shortName: "s",
      desc: "ayo belajar huruf s.",
      image: "/assets/images/s.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/S.webm",
    },
    {
      id: 20,
      name: "huruf t",
      shortName: "t",
      desc: "ayo belajar huruf t.",
      image: "/assets/images/t.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/T.webm",
    },
    {
      id: 21,
      name: "huruf u",
      shortName: "u",
      desc: "ayo belajar huruf u.",
      image: "/assets/images/u.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/U.webm",
    },
    {
      id: 22,
      name: "huruf v",
      shortName: "v",
      desc: "ayo belajar huruf v.",
      image: "/assets/images/v.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/V.webm",
    },
    {
      id: 23,
      name: "huruf w",
      shortName: "w",
      desc: "ayo belajar huruf w.",
      image: "/assets/images/w.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/W.webm",
    },
    {
      id: 24,
      name: "huruf x",
      shortName: "x",
      desc: "ayo belajar huruf x.",
      image: "/assets/images/x.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/X.webm",
    },
    {
      id: 25,
      name: "huruf y",
      shortName: "y",
      desc: "ayo belajar huruf y.",
      image: "/assets/images/y.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Y.webm",
    },
    {
      id: 26,
      name: "huruf z",
      shortName: "z",
      desc: "ayo belajar huruf z.",
      image: "/assets/images/z.webp",
      video: "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Z.webm",
    },
  ],
};

export default data;
